<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ac1b72f7-0700-46b4-ae0e-158822f8444c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bashta.Core\Bashta.Core.csproj" />
    <ProjectReference Include="..\Bashta.Infrastructure\Bashta.Infrastructure.csproj" />
  </ItemGroup>

</Project>
