// <auto-generated />
using System;
using Bashta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bashta.Infrastructure.Migrations
{
    [DbContext(typeof(BashtaDbContext))]
    partial class BashtaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bashta.Core.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameLocal")
                        .HasColumnType("text")
                        .HasColumnName("name_local");

                    b.Property<string>("TreatmentRecommendation")
                        .HasColumnType("text")
                        .HasColumnName("treatment_recommendation");

                    b.Property<decimal>("WateringModifier")
                        .HasColumnType("numeric")
                        .HasColumnName("watering_modifier");

                    b.HasKey("Id");

                    b.ToTable("disease", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.DiseaseDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("integer")
                        .HasColumnName("disease_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_healthy");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PlantId");

                    b.ToTable("disease_detection", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_type_id");

                    b.Property<DateOnly>("PlantedAt")
                        .HasColumnType("date")
                        .HasColumnName("planted_at");

                    b.Property<int>("PotId")
                        .HasColumnType("integer")
                        .HasColumnName("pot_id");

                    b.Property<DateOnly?>("RemovedAt")
                        .HasColumnType("date")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.HasIndex("PotId");

                    b.ToTable("plant", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.PlantPot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("firmware_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRainExposed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rain_exposed");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SensorReadingIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_reading_interval_minutes");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("plant_pot", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.PlantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxHumidity")
                        .HasColumnType("integer")
                        .HasColumnName("max_humidity");

                    b.Property<int>("MaxSoilMoisture")
                        .HasColumnType("integer")
                        .HasColumnName("max_soil_moisture");

                    b.Property<decimal>("MaxTemp")
                        .HasColumnType("numeric")
                        .HasColumnName("max_temp");

                    b.Property<int>("MinHumidity")
                        .HasColumnType("integer")
                        .HasColumnName("min_humidity");

                    b.Property<int>("MinLux")
                        .HasColumnType("integer")
                        .HasColumnName("min_lux");

                    b.Property<int>("MinSoilMoisture")
                        .HasColumnType("integer")
                        .HasColumnName("min_soil_moisture");

                    b.Property<decimal>("MinTemp")
                        .HasColumnType("numeric")
                        .HasColumnName("min_temp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameLocal")
                        .HasColumnType("text")
                        .HasColumnName("name_local");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("TargetDli")
                        .HasColumnType("numeric")
                        .HasColumnName("target_dli");

                    b.Property<int>("WateringIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("watering_interval_hours");

                    b.HasKey("Id");

                    b.ToTable("plant_type", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("recommendation", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.SensorReading", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("PotId")
                        .HasColumnType("integer")
                        .HasColumnName("pot_id");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric")
                        .HasColumnName("humidity");

                    b.Property<int?>("Lux")
                        .HasColumnType("integer")
                        .HasColumnName("lux");

                    b.Property<decimal?>("SoilMoisture")
                        .HasColumnType("numeric")
                        .HasColumnName("soil_moisture");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.HasKey("Time", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.WateringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmountMl")
                        .HasColumnType("integer")
                        .HasColumnName("amount_ml");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<bool>("IsForced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forced");

                    b.Property<int>("PotId")
                        .HasColumnType("integer")
                        .HasColumnName("pot_id");

                    b.Property<string>("SkipReason")
                        .HasColumnType("text")
                        .HasColumnName("skip_reason");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean")
                        .HasColumnName("skipped");

                    b.Property<int?>("SoilMoistureAfter")
                        .HasColumnType("integer")
                        .HasColumnName("soil_moisture_after");

                    b.Property<int?>("SoilMoistureBefore")
                        .HasColumnType("integer")
                        .HasColumnName("soil_moisture_before");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.Property<string>("WeatherSummary")
                        .HasColumnType("text")
                        .HasColumnName("weather_summary");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.ToTable("watering_event", (string)null);
                });

            modelBuilder.Entity("Bashta.Core.Entities.DiseaseDetection", b =>
                {
                    b.HasOne("Bashta.Core.Entities.Disease", "Disease")
                        .WithMany("DiseaseDetections")
                        .HasForeignKey("DiseaseId");

                    b.HasOne("Bashta.Core.Entities.Plant", "Plant")
                        .WithMany("DiseaseDetections")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Bashta.Core.Entities.Notification", b =>
                {
                    b.HasOne("Bashta.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bashta.Core.Entities.Plant", b =>
                {
                    b.HasOne("Bashta.Core.Entities.PlantType", "PlantType")
                        .WithMany("Plants")
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bashta.Core.Entities.PlantPot", "PlantPot")
                        .WithMany("Plants")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantPot");

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("Bashta.Core.Entities.PlantPot", b =>
                {
                    b.HasOne("Bashta.Core.Entities.User", "User")
                        .WithMany("PlantPots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bashta.Core.Entities.Recommendation", b =>
                {
                    b.HasOne("Bashta.Core.Entities.Plant", "Plant")
                        .WithMany("Recommendations")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Bashta.Core.Entities.SensorReading", b =>
                {
                    b.HasOne("Bashta.Core.Entities.PlantPot", "PlantPot")
                        .WithMany("SensorReadings")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantPot");
                });

            modelBuilder.Entity("Bashta.Core.Entities.WateringEvent", b =>
                {
                    b.HasOne("Bashta.Core.Entities.PlantPot", "PlantPot")
                        .WithMany("WateringEvents")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantPot");
                });

            modelBuilder.Entity("Bashta.Core.Entities.Disease", b =>
                {
                    b.Navigation("DiseaseDetections");
                });

            modelBuilder.Entity("Bashta.Core.Entities.Plant", b =>
                {
                    b.Navigation("DiseaseDetections");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Bashta.Core.Entities.PlantPot", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("SensorReadings");

                    b.Navigation("WateringEvents");
                });

            modelBuilder.Entity("Bashta.Core.Entities.PlantType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Bashta.Core.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PlantPots");
                });
#pragma warning restore 612, 618
        }
    }
}
